### ISSUE TITLE
automatically install python venv/apio like icestudio does

### ISSUE THREAD

**Issue by tinyfpga** [FPGAwars/apio-ide#24]
It would be very helpful if installation of apio-ide automatically installed a python venv and apio in the same way that icestudio does.

**Comment by tinyfpga** [comment]
By the way, I want to write a "getting started guide" for the TinyFPGA BX that uses Atom and APIO.  It should be as simple as "install Atom, then install the APIO plugin."

If I have to include instructions for installing Python and the APIO python package and setting up the PATH environment variable then many people will give up.

**Comment by Obijuan** [comment]
Apio-ide is now archived
