### ISSUE TITLE
After Apio updated to 0.4.0 Apio IDE 0.7.0 Error

### ISSUE THREAD

**Issue by faurbano** [FPGAwars/apio-ide#26]
After I updated Apio to 0.4.0. The APIO IDE stop working. I get a message related that version Apio should be less than 0.4.0.

**Comment by microbuilder** [comment]
Same issue simply following the guide here: https://tinyfpga.com/bx/guide.html

<img width="510" alt="screenshot 2018-12-08 at 02 29 09" src="https://user-images.githubusercontent.com/181073/49680087-20113280-fa91-11e8-9c9a-623934946c84.png">

**Comment by Obijuan** [comment]
Apio-ide is now archived
