### ISSUE TITLE
Pinout link for icestick links to spam site 

### ISSUE THREAD

**Issue by ghost** [FPGAwars/apio-ide#27]
https://github.com/FPGAwars/apio-ide/blob/05208eba98875019fce45f9d6e935742c77cc9a2/lib/main.js#L106

This link isn't valid, this domain is a parking service that redirects to ads.

**Comment by calincalin644** [comment]
I tried to correct it (branched, modified, commit, but the push was rejected). For the others, the official link is: https://www.latticesemi.com/view_document?document_id=50701

**Comment by Obijuan** [comment]
Apio-ide is now archived
