### ISSUE TITLE
Howto pass options to nextpnr or Yosys

### ISSUE THREAD

**Issue by bmentink** [FPGAwars/apio-ide#43]
I need some custom options to nextpnr like: `--ignore-loops --pcf-allow-unconstrained` etc ..
How do I do this, so that I can still build from the IDE ..

Also, how do I get Atom to leave the build console open .. it closes after each function ...

Many Thanks .... great package!

**Comment by bmentink** [comment]
Never mind. 
Helps if I read the APIO docs. The command `apio init --scons` creates a SConstruct file which I can modify ... works great.

**Comment by Obijuan** [comment]
Apio-ide is now archived
